### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by styfle** [SSAgov/ANDI#1]
I like this project! It is similar to [a11y.css](http://ffoodd.github.io/a11y.css/) but ANDI seems to have better navigation. Likely because ANDI is javascript and a11y is only css.

---

That being said, I think the "installation" instructions could be simplified to just start with, copy/paste the snippet. This should work in any browser.

It would be nice if the snippet was in the github readme as well.

**Comment by SSAgov** [comment]
Thank you for the suggestion. The installation page has been simplified.
