### ISSUE TITLE
Andi tool - language options issues?

### ISSUE THREAD

**Issue by vprentice** [SSAgov/ANDI#104]
Hello we received the following inquiry below:

Our website, EIA.gov, uses this code(<meta http-equiv="Content-Language" content="en-us" />) in the global header to specify page language.  ANDI consistently does not recognize this tag.  This is the ANDI output: (The <html> element does not have a lang attribute.)

William Jeffers
U.S. Energy Information Administration
Resource & Technology Management/Office of Stakeholder Outreach & Communications
1000 Independence Ave SW
Washington DC 20585
202-586-8416
william.jeffers@eia.gov
www.eia.gov

**Comment by JohnCotterSSA** [comment]
Hi William. Your code didn't get pasted into the github issue. Can you try again?

 In general the `<html>` element should define the lang for the page. Example: `<html lang="es">`

**Comment by vprentice** [comment]
Hello John please see the original email below with the code:


Hello Vince,

Coming full circle on this question. The DHS Accessibility Help Desk directed me back to you.  Our website, EIA.gov, uses this code(<meta http-equip="Content-Language" content="en-us" />) in the global header to specify page language.  ANDI consistently does not recognize this tag.  This is the ANDI output: (The <html> element does not have a lang attribute.)


William Jeffers
U.S. Energy Information Administration
Resource & Technology Management/Office of Stakeholder Outreach & Communications
1000 Independence Ave SW
Washington DC 20585
202-586-8416
***@***.******@***.***>
www.eia.gov<http://www.eia.gov/>

**Comment by JohnCotterSSA** [comment]
It's our understanding that the lang attribute is meant to be used to specify the language of the page, not meta tags. ANDI does not look at meta tags to determine page language.

Here is a reference on MDN which states: [If you want to indicate which language the document is written in, use the lang attribute instead)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Language)
