### ISSUE TITLE
ANDI does not provide the urls for iFrames that must be tested separately because ANDI does not test iFrames

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#11]
Since ANDI does not test iFrames it would be very helpful for ANDI to at least provide the url of iFrames on the page so that the user could navigate to those pages separately and attempt to run ANDI on those pages individually.

**Comment by SSAgov** [comment]
iFrames can be tested using ANDI, but must be tested individually. When a page has iFrames, ANDI presents a popup saying it has detected iFrames. Pressing cancel brings up ANDI’s frame selection menu and users can select an individual iframe including the url. A future update is going to do away with the popup, and require a button press to bring up the iframe selection menu.

**Comment by mraccess77** [comment]
Pressing ESC does not bring up the iframes selection menu for me.
https://labs.levelaccess.com/index.php/IFrame_Element

**Comment by SSAgov** [comment]
Thank you for providing the test page. We are successfully able to reproduce the issue using this link. Looking into it.

**Comment by SSAgov** [comment]
A new module has been added to handle the testing of iframes. When iframes are detected, “iframes” will appear in the module selection dropdown. Selecting the module will allow testers to open iframes individually in a new window. This approach works with the test page provided in this thread.
