### ISSUE TITLE
Hitting enter to navigate a link under the "Accessibility Alerts" list does not update focus when using JAWS

### ISSUE THREAD

**Issue by jcorradino** [SSAgov/ANDI#111]
A blind colleague of mine is trying to learn how to use ANDI for bug reporting, and has run into an issue with ANDI interacting with JAWS.  Typically, clicking a link in the "Accessibility Alerts" section sets the page focus on the element being reported - and I am able to see this piece working within JAWS... however, upon using the up and down arrow keys to orient herself within the page, nothing was happening on her end.  After sharing her screen, I observed the issue list under "Accessibility Alerts" scrolling up and down.

Issue observed in Chrome.

**Comment by JohnCotterSSA** [comment]
Thanks for the details. We'll try to replicate this issue and respond.

**Comment by JohnCotterSSA** [comment]
Do you happen to know the JAWS version that the user was using? We are having trouble replicating this issue.

**Comment by JohnCotterSSA** [comment]
Closing the issue. Will open it again if more details are supplied.
