### ISSUE TITLE
danger_anchorTargetNotFound is not written correctly

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#116]
danger_anchorTargetNotFound is referenced in landi.js alert_0069. When you go to alert_0069 in andi.js, it says that the alert is a "warning" (var alert_0069 = new Alert("**warning**","6","In-page anchor target with [id=%%%] not found.","anchor_target_not_found");). This is also shown for danger_anchorTargetNotFound (this.**danger**_anchorTargetNotFound = makeIcon("**warning**","In-page anchor target not found");

This means that danger_anchorTargetNotFound should switch to warning_anchorTargetNotFound, or the other areas should change from "warning" to "danger"

**Comment by JohnCotterSSA** [comment]
Fixed in landi 8.1.1
Thank you
