### ISSUE TITLE
in tandi.js, hasHeaderRow and hasHeaderCol variables are not being used

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#118]
When I was looking through the variables in tandi, I noticed that the hasHeaderRow and hasHeaderCol variables are only used twice, once when they are made, and once when the value can be changed to true. These variables are not used anywhere else in the program, and should probably either be used or removed from the code.

**Comment by JohnCotterSSA** [comment]
Fixed in tANDI 11.1.1
Thank you.
