### ISSUE TITLE
Hosting ANDI on a Prison Server

### ISSUE THREAD

**Issue by pshikli** [SSAgov/ANDI#119]
I have tried to follow the instructions at
https://www.ssa.gov/accessibility/andi/help/faq.html#hostYourOwn
because we have accessibility analysts who are inmates in a prison and certified Trusted Testers. Their LAN has no internet access because they are not allowed unmonitored internet access. The prison's IT folks can access their LAN and the internet. We have modified the andi.js file as instructed, yet can't get it to come up in any of the browsers available to the inmates. No error messages; just a silent failure to load.

Anybody with some experience hosting a copy of ANDI willing to consult on this? I have a feeling that looking over our andi.js and a short conversation would produce the aha moment.

Cheers,
Peter Shikli
Access2online Inc.
29030 SW Town Center Loop East
Suite 202-187
Wilsonville, OR 97070
503-570-6831 - pshikli@access2online.com
Cell: 949-677-3705
FAX: 503-582-8337
www.access2online.com
Prison inmates helping the internet become accessible

**Comment by JohnCotterSSA** [comment]
Issue has been resolved.
