### ISSUE TITLE
ANDI does not indicate when an ismap attribute is present warning of a server-side image map

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#12]
It would be helpful if ANDI warned the user if a server side image map was found via the ismap attribute.

**Comment by SSAgov** [comment]
The graphics/images module (gANDI) will detect <img> tags with the ismap attribute, and throw a Danger Alert.

**Comment by mraccess77** [comment]
Here is a link to a page that has an image with an ismap attribute
https://labs.levelaccess.com/index.php/Ismap

**Comment by SSAgov** [comment]
Thank you for the test page. This is has been fixed in gANDI version 4.6.4
