### ISSUE TITLE
ANDI won't run on some websites

### ISSUE THREAD

**Issue by A11Ybot-OP** [SSAgov/ANDI#126]
Hi, ANDI won't run on some websites, I tested it on IE, Chrome and FireFox, other websites works fine tho, thx.

e.g 
https://www.barclays.co.uk/

https://www.bing.com/search?q=abc&form=QBLH&sp=-1&pq=abc&sc=8-3&qs=n&sk=&cvid=EA12CF629E0C42A1BC7A6DEBF4879200

**Comment by JohnCotterSSA** [comment]
Hello! Some websites have enforced a Content Security Policy directive which prevents malicious, external scripts from being injected into the page for security reasons. If you press F12 and launch ANDI, you will know if CSP is blocking ANDI if you see a message appear in the F12 Console. The barclays site does appear to have CSP.

Please refer to the ANDI FAQ page for help resolving this issue and continue testing with ANDI. 
https://www.ssa.gov/accessibility/andi/help/faq.html#wontLaunch
Select "Why Won't ANDI work on this page?" to find a solution that works for you.
