### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by freddieh009** [SSAgov/ANDI#127]
I am having a hard time installing the ANDI software in Chrome and Explore 
Can you tell me what would be the best way of getting this taken care of

I cant finish the Office of Accessible Systems & Technology (OAST) Training

**Comment by JohnCotterSSA** [comment]
Hi. Sorry you're having a hard time with this.

The installation should be simple. If you are a mouse user, it's a drag and drop. If you're a keyboard user, it's a few extra strokes. 

On the [ANDI Install page](https://www.ssa.gov/accessibility/andi/help/install.html#install), scroll down a bit and you'll see a section called "Installation Help" which will walk you through it depending on what browser you use.
