### ISSUE TITLE
iANDI has text that makes it look like the code was copied from fANDI without fixing all the comments

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#133]
iandi.js has some comments that makes it look like the code for iANDI was copied from fANDI without fixing all of the comments.

They are:

- At line 2 where the code for the module name is put, there is this text: "**fANDI: focusable elements** ANDI **(default mode)**"
- At line 12, there is this comment: "//This function will analyze the test page for **focusable element** related markup relating to accessibility"
     - This is ironic, because in line 14, there is this code: "andiCheck.common**NonFocusableElement**Checks(andiData, $(this), true)"

**Comment by JohnCotterSSA** [comment]
comments fixed. Thanks.
