### ISSUE TITLE
can't open ANDI on website

### ISSUE THREAD

**Issue by kelsey-a0715** [SSAgov/ANDI#136]
https://instantink.hpconnected.com/us/en/l/v2?jumpid=va_65bsqvipye
I can open on the login page, not on the homepage. I've tried refreshing and disabling CSP...javascript recommends using strict CSP but I'm new to all this.

**Comment by JohnCotterSSA** [comment]
It looks like CSP is blocking ANDI here. Turning on the CSP disabler doesn't seem to be having an effect.

You may try to contact the site admin and request that the ANDI script are whitelisted. Otherwise, ANDI might not be able to be used to test this site.
