### ISSUE TITLE
"presentation" role isn't taken into account by ANDI

### ISSUE THREAD

**Issue by marco-c** [SSAgov/ANDI#138]
If an element has the role attribute set to `presentation`, it shouldn't have an accessible name according to MDN (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role), but ANDI requires it.

![immagine](https://user-images.githubusercontent.com/1616846/174553892-5c35a7eb-22bd-4b12-87c3-1b6ea0aae005.png)

See also https://github.com/mozilla/pdf.js/issues/14437.

**Comment by rgutierrezatx** [comment]
@JohnCotterSSA can you respond to this.  This ticket was opened in june and at least can you comment on it?  We have to keep delaying changes to our system because of this.

**Comment by JohnCotterSSA** [comment]
You are correct. That looks like an issue with ANDI. ANDI should not be throwing the "no accessible name" alert for a role=presentation element. We'll fix it.

**Comment by JohnCotterSSA** [comment]
ANDI 28.0.3 resolved this. If a canvas is not focusable and has role=presentation or role=none, it will not throw the "no accessible name" alert. Thanks for finding this issue!
