### ISSUE TITLE
ANDI wouldn't work on Chrome and now I can't view images on my website in Chrome

### ISSUE THREAD

**Issue by Amycofsf** [SSAgov/ANDI#139]
ANDI wouldn't load my website in Chrome, so I uninstalled the bookmark, and now my org's website won't load all images.  At first, the images would still load in other Chrome profiles.  I tried about 10 different fixes ([listed here](url)).  Uninstalling and reinstalling Chrome caused all of my profiles to no longer load the images.  They still load in Edge and other browsers.  I'm the admin of my org's website.  Nothing has changed on the backend that would cause this.  Something with the ANDI bookmark messed up my Chrome profile.  I have already contacted Google to ask for help.  What can I do?

**Comment by JohnCotterSSA** [comment]
Wow, I'm sorry to hear about this. There is no reason ANDI would cause this. Hopefully you can find the cause.
