### ISSUE TITLE
Code may be unnecessary in hANDI

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#140]
The code: $(element).css("text-indent") != "0" || $(element).css("text-indent") != "0px" on line 72 of hANDI.js may be unnecessary because in the same if statement, it is checked if "text-indent" is less than -998.

If the condition with parseInt is True, then that means that the other conditions are also true. And if the value of parseInt goes to 0, then it should not be less than -998.

**Comment by JohnCotterSSA** [comment]
Good catch. Fix incoming
