### ISSUE TITLE
html5hidden attribute is unnecessary in hANDI

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#142]
I have recently learned that the html5 hidden attribute can be overridden by using a display style.

This means that if an element with a hidden attribute is hidden then the attribute would also have a hidingType of display:none. 

Source Information: https://meowni.ca/hidden.is.a.lie.html

**Comment by JohnCotterSSA** [comment]
This is true, browsers usually translate the hidden attribute into display:none, but the hidden attribute still appears in the DOM, so I think it's still useful to know exactly how the element was hidden when using the hidden attribute.
