### ISSUE TITLE
Automate running ANDI on multiple pages

### ISSUE THREAD

**Issue by kamal2222ahmed** [SSAgov/ANDI#145]
Make ANDI available as an Automated tool, where we can specify parameters like:

1. Pages
2. Base Page ( starting page ) and a number representing depth to crawl 
3. Filter domains ( This will give us the ability to filter external domains )
4. Specify A, AA, or Both
5. Map WCAG 2. x Rules to the scan result
6. Specify remedial measures, as listed on the W3C site
7. Ability to run from the command line, so it can become part of the SDLC pipeline
8. Perhaps integrate with tools like Cypress so it can leverage functionality from other tools

**Comment by ollie-iterators** [comment]
That sounds good, but maybe we should start with asking for making it easier for the people at the Accessible Solutions Branch at SSA to notice new issues and respond to them.

**Comment by rgutierrezatx** [comment]
it would be nice if they did.  the lack of response on this github tells me how much they care about accessibility

**Comment by JohnCotterSSA** [comment]
> it would be nice if they did. the lack of response on this github tells me how much they care about accessibility

Sorry for the delay in response. We care very much about people with disabilities and are major advocates of accessibility.

Regarding converting ANDI to an automated tool, these are great ideas, and would certainly be useful. ANDI is a tool to be used for manual inspection, and that will not change. There are many other tools that can be used to perform automated scanning and that handle these parameter ideas.
