### ISSUE TITLE
I think TestPageData.allVisibleElements should also filter by if the element is hidden using the hidingTypes used in hANDI

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#146]
I have noticed that some elements that are said to be visible on certain pages are actually not visible, and are using hidingTechniques like opacity.

It would be good to have allVisibleElements use those tools to filter out elements that are not visible on the page.

**Comment by JohnCotterSSA** [comment]
Good idea, but that we be quite a performance hit and would slow down ANDI's snappiness. Let me know if can provide a code example of the problem, and I'll reopen the issue.
