### ISSUE TITLE
tANDI improvement - ARIA role="table"

### ISSUE THREAD

**Issue by drewnielson** [SSAgov/ANDI#15]
ANDI currently does not account for tables constructed following the [WAI-ARIA table design pattern](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/#table). 

Also see [WAI-ARIA table example](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/table/table.html).

**Comment by SSAgov** [comment]
tANDI (ANDI tables) will now detect ARIA tables using role=table
