### ISSUE TITLE
I found gANDI508- classes on the page when I was on the links/buttons page for ANDI

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#151]
When I was inspecting the page, I found that gANDI508-background was stil attached to certain elements after I went from graphics to links on ANDI.

**Comment by ollie-iterators** [comment]
I commented out .cleanup on gANDI and the code looks like it is behaving the same as it was before it was commented out. I am wondering if the cleanup function actually does anything now.

**Comment by JohnCotterSSA** [comment]
Nothing gets by you! :)  Another good catch. 

The cleanup function definitely works, but it looks like, in gANDI, it was expecting the gANDI508-background class to always  be on elements with .ANDI508-element. However, that is not always the case. I fixed this issue in gANDI 6.1.1
