### ISSUE TITLE
Some classes with lANDI508- were found when not using lANDI

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#155]
Some classes (lANDI508-nextTab and lANDi508-anchorTarget) were found when using modules other than lANDI.

**Comment by JohnCotterSSA** [comment]
The lANDI508-nextTab class gets applied to certain buttons in the lANDI table (View Links List). The button only appears when ANDI detects an internal link. The "Next Tab" button was a very specific feature request to help test internal links. 

We weren't able to reproduce these classes appearing in other modules other than lANDI.
