### ISSUE TITLE
It should be possible to create a common .cleanup function for the different modules

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#156]
I think it would be a good idea to make a common cleanup function for all the modules that accepts a list of strings that represent the various things that should be removed when going to a different module.

**Comment by JohnCotterSSA** [comment]
Each module needs to implement the cleanup function and it does so in the most efficient way possible. Efficient cleanup is more complex than passing a list of strings, classes, attributes, etc.
