### ISSUE TITLE
tabindex in createOverlay could be given a default value of 0

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#159]
Since in the createOverlay function, if tabindex is not given a value means that it is given a value of 0, it means that you could give tabindex a default value of 0. The parameter is even already at the end of the list of parameters for the function.

**Comment by JohnCotterSSA** [comment]
Not sure what you mean. The overlay sometimes needs to take on the tabindex value of the element it associates with. That value is passed in as a parameter to the function. If a tabindex is not passed it, the overlay defaults to zero.
