### ISSUE TITLE
The longdesc attribute is deprecated

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#161]
It says that in this url: https://www.w3schools.com/tags/att_img_longdesc.asp, that longdesc is not supported in the major browsers. Because of this, I think it can be removed from gANDI.

**Comment by fstrr** [comment]
`longdesc` does have some support in major browsers, but it's inconsistent. That said, and related to this, there is [an issue and related pull request to remove the Using Longdesc technique from WCAG](https://github.com/w3c/wcag/issues/2502).

**Comment by JohnCotterSSA** [comment]
We agree that it is no longer supported, however we think it is helpful to know about its presence while testing. Some AT may still support the legacy attribute.
