### ISSUE TITLE
ANDI Does not work on our Web Application

### ISSUE THREAD

**Issue by dqiu1200** [SSAgov/ANDI#165]
Browser used for testing: MS Edge, Version 106.0.1370.42.

1.  On the web application page, when I tried to open ANDI by clicking on it from the favorite bar, nothing happened, ANDI could not be launched at all on the application. 
2.  After our developer made some changes to the web application, I was able to launch ANDI, but it did not function.  Detail issues are:

a.	The webpage’s header being cut off
b.	ANDI did not scan the page and no result returned at all
c.	On the ‘Select Module’ dropdown, only ‘focusable elements’ is available. When clicking on the dropdown, nothing happened, and I was not able to see/select other modules other than ‘focusable elements’.

**Comment by JohnCotterSSA** [comment]
Hi, It sounds like a Javascript error might be occurring which is causing ANDI to not fully load.

Can you please open dev tools and go to the console tab, then launch ANDI and let us know what errors you see? Screenshot of dev tools console will be helpful.

**Comment by JohnCotterSSA** [comment]
It looks like the website has a CSP policy which is blocking ANDI from working. There are workarounds to CSP documented here: https://www.ssa.gov/accessibility/andi/help/faq.html#wontLaunch

![image](https://user-images.githubusercontent.com/55763887/196462763-fed1796f-606c-498c-bc42-b7cf381ccc15.png)

The boostrap error is not related to ANDI
