### ISSUE TITLE
These variables are not being used

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#169]
1. var adjustedShade; (Line 308 in candi.js)
2. src (Line 134 in iandi.js)
3. prevNextButtons (Line 664 in landi.js)
4. var x; (Line 1154 in tandi.js)
5. referencedId (Line 1446 in tandi.js)
6. headersText (Line 1568 in tandi.js)
7. message (Line 1581 in tandi.js)
8. function index_greaterThan(a,b){ (Line 1683 - 1698 in tandi.js)

**Comment by JohnCotterSSA** [comment]
fixed. Thank you.
