### ISSUE TITLE
andi.css CSS performance issues

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#170]
1. Element (span.ANDI508-overlay.ANDI508-overlay-alert) is overqualified, just use .ANDI508-overlay-alert without element name. (#ANDI508-testPage span.ANDI508-overlay.ANDI508-overlay-alert) (Line 42)
2. Element (img.ANDI508-highlightIcon) is overqualified, just use .ANDI508-highlightIcon without element name. (#ANDI508 img.ANDI508-highlightIcon) (Line 48)
3. The universal selector (*) is known to be slow. (#ANDI508 *::before,) (Line 102)
4. The universal selector (*) is known to be slow. (#ANDI508 *::after,) (Line 104)
5. The universal selector (*) is known to be slow. (#ANDI508 *:after) (Line 105)

**Comment by JohnCotterSSA** [comment]
We definitely appreciate efficient CSS, however, ANDI's CSS needs to have very high specificity to be able to override styling that the test application may apply to elements.

The universal selector is slow for sure, but It is unavoidable in instances 3,4,5 above.
