### ISSUE TITLE
Commented out code in andi.js

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#171]
On line 3522, there is the code "/*&& ( !role || role === "img" )*/", which is commented out and not doing anything. If it is unneeded, then it should be removed.

**Comment by JohnCotterSSA** [comment]
Thank you. fixed in 28.0.9

**Comment by ollie-iterators** [comment]
I don't see 28.0.9 in SSAgov/ANDI

**Comment by JohnCotterSSA** [comment]
just pushed.
