### ISSUE TITLE
Unknown CSS Properties used

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#174]
These CSS Properties are not known CSS Properties:
1. scrollbar-arrow-color (Line 108 in andi.css)
2. scrollbar-face-color (Line 109 in andi.css)
3. scrollbar-track-color (Line 110 in andi.css)
4. scrollbar-arrow-color (Line 231 in andi.css)
5. scrollbar-face-color (Line 232 in andi.css)

**Comment by JohnCotterSSA** [comment]
These are for IE
