### ISSUE TITLE
Make ANDI be available as a Library to facilitate automation

### ISSUE THREAD

**Issue by kamal2222ahmed** [SSAgov/ANDI#175]
If ANDI is available as a library ( example = axe-core from [Deque Systems](https://www.deque.com/) ) . This will facilitate it being used throughout Software Development Life Cycle, and included in the CI/CD pipelines.

**Comment by JohnCotterSSA** [comment]
We appreciate your interest in ANDI.

ANDI is a manual inspection tool. We have no plans to make it like axe core.
