### ISSUE TITLE
ANDI not functioning on ServiceNow "Tokyo" release

### ISSUE THREAD

**Issue by stevekram** [SSAgov/ANDI#184]
Hello, 
Our organization recently updated one of their ServiceNow environments from "Rome" to "Tokyo" (see https://www.servicenow.com/community/now-platform-articles/servicenow-versions/ta-p/2312014).  ANDI works successfully on the older "Rome" in both Chrome and Firefox, but results in a blank locked-up session using "Tokyo".  This is repeatable in current versions of Chrome, FireFox, and Edge.  We see no indications why activating ANDI results in the ServiceNow screen becoming unresponsive.  Screen capture shows ANDI functionality on "Rome" ServiceNow page, and the same page when activating ANDI using ServiceNow "Tokyo".

Thanks.

Steve
![ANDI-servicenow screen captures](https://user-images.githubusercontent.com/122641984/212406252-4f963391-41e3-459b-b31a-184e19e760d3.png)

**Comment by JohnCotterSSA** [comment]
Hi Steve. Please see if answers/workarounds on the FAQ page addresses this issue for you:

https://www.ssa.gov/accessibility/andi/help/faq.html#lby-wontLaunch

**Comment by stevekram** [comment]
John,

Since we can successfully run ANDI on the “R”ome version of ServiceNow (verified in various browsers) but not “T”okyo, we feel we’ve eliminated CSP and Huge Test Page as potential causes.  The JavaScript “favelet test” runs successfully, but we did note one new “Uncaught SyntaxError” when we launch ANDI.

***@***.***
We’ve verified this does NOT appear in the previous ServiceNow environment.

Hopefully this helps.

Steve Kram

**Comment by JohnCotterSSA** [comment]
Can you please provide the error info (line number) for the syntax issue?

**Comment by stevekram** [comment]
John,

Clicking the error message’s hot link marks line 7 of VM12321 9289854533f1d2dd3c7cd298d8908667.jsdbx

//code//
import {lodash as __TEMP__lodash_4_17_4} from '/uxasset/externals/js-common-mega/bundled-assets.jsdbx';


***@***.***

**Comment by JohnCotterSSA** [comment]
That isn't a reference to anything that ANDI is using. I would assume that error might be present before ANDI is launched.

If you've already ruled out presence of iframes by following the FAQ, then the other thing that may cause the issue is if the page is rendered using shadow DOM. At this time, ANDI cannot detect shadow DOM content.

**Comment by stevekram** [comment]
John,

I carefully re-executed the iframes work-around actions, and am now able to operate ANDI on the “T”okyo version of ServiceNow.  😊

Do we forever need to apply this work-around, or is there a update planned for ANDI that will handle ServiceNow’s iframes implementation?

Thanks.

Steve K.

**Comment by JohnCotterSSA** [comment]
Unfortunately, there isn't a way with ANDI to make this more streamlined. It's a limitation of what abilities browsers allow for externally executed scripts.

**Comment by stevekram** [comment]
We understand.  Thanks for checking, John.

Steve K.
