### ISSUE TITLE
jQuery fails to load 

### ISSUE THREAD

**Issue by mustang492** [SSAgov/ANDI#203]
Good Morning,

I setup ANDI on a webserver in my domain.  The DEV environment does not have access to external sites.  I am stuck at (andi.js) "modify the jqueryDownloadSource location to a custom jquery location".  ANDI.js keeps trying to the download jquery from the CDN listed in line 4099 "jqueryDownloadSource".  I downloaded jQuery 3.6.0 and placed it in my ANDI directory /jquery/js and tried to modify lines 4122 & 4123 FROM script.src = jqueryDownloadSource + jqueryPreferredVersion + "/jquery.min.js"; TO "**D:\Program Files\App\andi\jquery\js**" + "**3.6.0**" + "/jquery.min.js"; without success.  I cant figure out how to get ANDI to find the local jquery version.  I am limited in coding skills, which is probably apparent.  Thank you for any assistance you can provide.

**Comment by JohnCotterSSA** [comment]
I was just getting read to reply and say you will also need to host and reference your own jquery instance. Glad you got it rolling.

**Comment by mustang492** [comment]
Thanks John.  I just kept grinding away until I got it.  Is it possible to dedicate one server to host and reference my jquery to support multiple servers in my domain?  Again, thank you
