### ISSUE TITLE
whether or not to hide alerts should be in tANDI.viewList_toggle

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#204]
For the other modules (like lANDI), the place where the code for hiding or showing alerts lists is in viewList_toggle. This is not true in tANDI. I think it would be better if the function viewList_toggle matched for lANDI in tANDI.

**Comment by JohnCotterSSA** [comment]
The `viewList_toggle` function is for showing the elements lists: Links list, Table list. Not the alert list.
