### ISSUE TITLE
Code for $("#ANDI508-viewOutline-button") in sANDI.js is simillar to lANDI.viewList_toggle

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#206]
Code in $("#ANDI508-viewOutline-button") is simillar to lANDI.viewList_toggle. Basically the only thing that is different is the order of the code because the if condition for "aria-expanded" is set to true rather than false, and the name of the class in the slideUp or slideDown line.

**Comment by JohnCotterSSA** [comment]
Thanks for this observation.
