### ISSUE TITLE
The lang property in the langAttributes-button in sANDI could be found by using the .attr() function instead of the .prop() function

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#208]
The lang property in the langAttributes-button in sANDI could be found by using the .attr() function instead of the .prop() function. This would make it more simillar to the roleAttributes function and could make it easier to condense the two functions into one function that is referenced twice in the module.

**Comment by eron420** [comment]
Who the f is this?

**Comment by Bostonchik** [comment]
Who the fuck are you? 


Sent from the all new AOL app for iOS


On Wednesday, June 7, 2023, 1:19 PM, eron420 ***@***.***> wrote:



Who the f is this?

**Comment by eron420** [comment]
Why am I getting this email?

**Comment by JohnCotterSSA** [comment]
Thanks for analyzing the code. A reusable function to search for different kind of attributes and supply the overlay could be a nice code clean up.
