### ISSUE TITLE
id in the overlayTableMarkup function could be found by using the .attr() function

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#209]
The id value in the overlayTableMarkup function could be found by using the .attr() function.

This would allow the code to be condensed to use a for loop with a list containing the attributes that are being looked for.

**Comment by JohnCotterSSA** [comment]
Thanks for looking into the code and making a recommendation.

This function already is a loop, and .id performs faster than jquery .attr()

**Comment by ollie-iterators** [comment]
I'm talking about "AndiOverlay.prototype.overlayTableMarkup" in line 1533. The for loop would replace the if statements: "if(role)", "if(id)", "if(headers)", and "if(scope)".
