### ISSUE TITLE
ANDI closes Oracle via coldfusion popup 

### ISSUE THREAD

**Issue by NguyenLinhepa** [SSAgov/ANDI#216]
ANDI works with Oracle via Coldfusion normal page, but it closes when there is a popup.

**Comment by JohnCotterSSA** [comment]
When you say ANDI closes, do you mean it disappears when the popup is launched? If that's the case, I assume that when the page's popup appears, it is actually redirecting the user to a new page which would naturally cause ANDI to disappear. ANDI doesn't persist on the page when navigating to a new page.

**Comment by NguyenLinhepa** [comment]
User logged in to the app, click on ANDI and ANDI works.  Then, user click on button to launch a popup, application logout user and ANDI disappears.

**Comment by JohnCotterSSA** [comment]
Thanks for clarifying. It's tough for me to guess what's happening here without being able to see it in action.

**Comment by NguyenLinhepa** [comment]
I am guessing that Javascript on ANDI and Coldfusion has a conflict or some security issue.
