### ISSUE TITLE
Five buttons top-right fail to render correctly

### ISSUE THREAD

**Issue by CodaCodr** [SSAgov/ANDI#218]
Here's how they look on my screen:

![image](https://github.com/SSAgov/ANDI/assets/436812/8f08daed-5d6a-4a26-8447-28dfab47b043)

Win10, Firefox latest.

New user!

**Comment by JohnCotterSSA** [comment]
It could be that some CSS on the site you are testing is interfering with ANDI's styles to make those images appear on the ANDI buttons. Can you please try ANDI on a few different websites to see if the problem is consistent for you on Firefox?

**Comment by CodaCodr** [comment]
I haven't been able to repeat this :/ Closing.
