### ISSUE TITLE
Hosting instance of ANDI

### ISSUE THREAD

**Issue by dmtrs4renzic** [SSAgov/ANDI#219]
I followed the instructions located at https://www.ssa.gov/accessibility/andi/help/faq.html#hostYourOwn.  When I click the bookmark on a website, nothing happens.  Using the developer tools in Chrome, I can see the javascript is added to the page.

Browser: Version 117.0.5938.92 (Official Build) (64-bit)
OS: Windows 11

**Comment by dmtrs4renzic** [comment]
I think it's a browser security thing.  Closing.

**Comment by dmtrs4renzic** [comment]
I think this is due to a browser security feature.

**Comment by JohnCotterSSA** [comment]
Browsers prevent local scripts from executing on web server pages for security. To solve your issue, you either need to a) Run ANDI locally and limit your testing to local pages only, or B) host ANDI on a web server, and then you may test test web-served pages.
