### ISSUE TITLE
ANDI incorrectly identifying duplicate ids

### ISSUE THREAD

**Issue by kjenks2016** [SSAgov/ANDI#22]
when I run ANDI in an application there are multiple buttons on the screen called “View Form”  ANDI identified the ids for these as Duplicate ids – however the markup shows the ids as viewFormButton_0, viewFormButton_1, viewFormButton_2 etc.  These should not be identified as duplicate ids because the developer has added the -0, -1, -2 to make them each unique.   
![2018-07-03_13-10-57](https://user-images.githubusercontent.com/19271183/42234515-594b4870-7ee4-11e8-8fed-f3869cb61442.jpg)

**Comment by SSAgov** [comment]
ANDI has been updated with smarter detection of duplicate ID. This should cut down on some "noise" and only alert you to duplicate ID issues that are related to accessibility. (when the duplicate is referenced by an accessibility component such as aria-labelledby).
If you test the page in your screenshot again, you will probably not see these alerts.
