### ISSUE TITLE
ANDI causes page to reload but the page never reloads

### ISSUE THREAD

**Issue by johnscub11** [SSAgov/ANDI#220]
I have a web page that loads and works correctly but, when I open ANDI, it forces the page to reload but the page never reloads.
This page is inside a ServiceNow image.
![TTH Screen shot After starting ANDI](https://github.com/SSAgov/ANDI/assets/86496824/866a7e9e-8eaa-493e-ab75-a2d45282bf67)
![TTH Screen shot before starting ANDI](https://github.com/SSAgov/ANDI/assets/86496824/4a9ad0d4-6710-4981-a92c-fe67f3eabc9a)

Please let me know what additional information you need.
Email: DAVID.JOHNSON@associates.hq.dhs.gov

**Comment by JohnCotterSSA** [comment]
What is probably happening is that the content you want to test is inside of an iframe. Sometimes iframes are built in a way that when ANDI is launched, the iframe content gets removed - It's a browser security feature. Please try the instructions in this workaround: https://www.ssa.gov/accessibility/andi/help/faq.html#iframeFix

**Comment by johnscub11** [comment]
I just found the issue. The application uses Shadow DOMS for each of the cards you see in the screen shot above and, based on the ANDI docs, it can't handle Shadow Doms.
Is there any development work being done to handle these?

**Comment by JohnCotterSSA** [comment]
At this time, ANDI cannot inspect shadow DOM content.
