### ISSUE TITLE
In Firefox: ANDI Output of "-moz-alt-content" for images with alt="" AND missing alt

### ISSUE THREAD

**Issue by cliffbert** [SSAgov/ANDI#223]
e.g. at https://acrttool.github.io/DecorativeImage/

ANDI shows the following:

Accessibility Components: 4
alt: 	""
innerText: -moz-alt-content
::before: 	-moz-alt-content
src:   	.\Mountain.jpg
ANDI Output:
-moz-alt-content

**Comment by JohnCotterSSA** [comment]
This Firefox bug has been avoided in ANDI 29.0.1
