### ISSUE TITLE
ANDI does not launch.

### ISSUE THREAD

**Issue by jbANDI123** [SSAgov/ANDI#227]
ANDI has stopped working. When selected, the tool doesn't drop down. I've tried your troubleshooting page with no luck.

**Comment by jbANDI123** [comment]
When I click on ANDI to launch, the inspection tools are not dropping down. I've tried several different web pages.

**Comment by Emmarie-Ahtunan** [comment]
I'm following SSAgov. I just tried to get ANDI to work from my bookmarks toolbar. That didn't work; it's not currently launching from my bookmarks. I needed to go into my applications folder and open ANDI from there. I hope that helps!

**Comment by jbANDI123** [comment]
Thank you, Emmarie! Can you give more details on going into your application folder? 

I also tried to remove then add ANDI back to my tool bar, and it didn't work.

**Comment by Emmarie-Ahtunan** [comment]
Are you opening ANDI from your bookmarks on an actual webpage?

<img width="850" alt="Image of ANDI open on GitHub Accessibility webpage." src="https://github.com/SSAgov/ANDI/assets/86572370/982247d8-be83-4e14-8aeb-1c82b21d43c9">

**Comment by jbANDI123** [comment]
Yes

**Comment by Emmarie-Ahtunan** [comment]
Now that I've deleted and reinstalled ANDI, it's working fine for me. Have you updated Chrome? I think I had an update yesterday or the day before. Otherwise, maybe check the troubleshooting page or do as @JohnCotterSSA asks: Can you provide any other details? Check the developer tools console for errors. Provide a link to a page that it's not working on.

Best!

**Comment by dilitimor** [comment]
Andi also did not run for this site https://indonesia.go.id
It is work for others

**Comment by dilitimor** [comment]
> Andi also did not run for this site https://indonesia.go.id It is work for others

It is solved, use CSP disable extension, and refresh (my mistake is not refresh) than run ANDI

**Comment by JohnCotterSSA** [comment]
Thank you for troubleshooting the issue. I will close the ticket.
