### ISSUE TITLE
Please let us customize hotkeys

### ISSUE THREAD

**Issue by Zireael07** [SSAgov/ANDI#237]
For some reason, my browser totally fails to detect Alt key presses :/

**Comment by JohnCotterSSA** [comment]
What browser are you using?

**Comment by Zireael07** [comment]
Vivaldi

(I think the failure is because I am running a custom remapper program so that LAlt is effectively Shift, but as a minimum AltGr aka RAlt should be treated as alt)

**Comment by Zireael07** [comment]
Why close as completed? Last commit was 3 months ago and I see nothing about AltGr being equal to LAlt

**Comment by JohnCotterSSA** [comment]
Thank you for your interest in ANDI. Unfortunately, the ability to customize hot keys is not a feature we will be adding at this time.

**Comment by Zireael07** [comment]
Understandable, but then you should use the "close as not planned" feature so that it is clear
