### ISSUE TITLE
Version with no external downloads

### ISSUE THREAD

**Issue by acorpuz101** [SSAgov/ANDI#241]
Can we get a hosted version/build that includes the jquery library in the andi.js ? It'd be useful in more restricted environments where we'd be able to allow the andi tool but not the external jquery download.

**Comment by JohnCotterSSA** [comment]
ANDI downloads its jquery version from a google hosted library at https://ajax.googleapis.com/

One thing to note: If the webpage you are testing has jquery included, and the version is _not too old_, ANDI will attempt to use that version/download of jquery, and will not download its own copy from the CDN.

For utmost security, you may want to host your own version of ANDI on your org's internal web servers and point your version to your own hosted instance of jquery.
