### ISSUE TITLE
ANDI not working in Windows 11

### ISSUE THREAD

**Issue by ericaps52** [SSAgov/ANDI#243]
Good day,

I use ANDI to test software applications for 508 compliance.  The ANDI tool worked on Windows 10.  I upgraded my laptop to Windows 11 and now ANDI no longer works. Please help.

Thank you in advance.

**Comment by JohnCotterSSA** [comment]
Sorry you are having this trouble. Most likely your system admin changed a setting in the browser to prevent scripts like ANDI from launching from a bookmark. Follow this link: https://www.ssa.gov/accessibility/andi/help/faq.html#wontLaunch and follow the steps under "Check if favelets are blocked". If favelets are blocked for you, I suggest contacting your system admin.
