### ISSUE TITLE
tiny, low-contrast text in ANDI element descriptions

### ISSUE THREAD

**Issue by rtharperuillinois** [SSAgov/ANDI#244]
This image should show the issue:
![image](https://github.com/user-attachments/assets/cbea7083-84c8-4c39-8513-e2a2e8ca3907)

**Comment by JohnCotterSSA** [comment]
If you are referring to the ID in the aria-labelledby reference list, the ID is intentionally smaller. The [contrast is 7:01:1](https://webaim.org/resources/contrastchecker/?fcolor=959595&bcolor=000000)
