### ISSUE TITLE
Table Analysis Mode not available to change

### ISSUE THREAD

**Issue by nickywolfe-vd** [SSAgov/ANDI#246]
![image](https://github.com/user-attachments/assets/bf66197c-51f3-4694-aaa7-ccbf5bf1cf07)
https://www.ssa.gov/accessibility/andi/help/modules.html#tANDI-tableAnalysisMode

There is no way to be found to change the table analysis mode like the documentation suggests.

**Comment by JohnCotterSSA** [comment]
Hello. If ANDI doesn't detect that headers/id are being used, then it doesn't display that table analysis mode switch because there is not point in switching into that mode. Assume that the scope analysis mode is activated if headers/id aren't found on table cells.
