### ISSUE TITLE
Support aria-activedescendant

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#25]
ANDI is a great tool and there have been many recent improvements to make it the master tool.  There remain a few ARIA related items such as support for aria-activedescendant that might be useful where this type of thing is implemented with radiogroup, tree, tablist, grid, etc.

See the first example on this page for a structure that uses aria-activedescendant.
https://labs.levelaccess.com/index.php/ARIA_Radio_and_Radiogroup

**Comment by SSAgovAdmin** [comment]
Thank you - We're glad that you're finding ANDI to be your master accessibility testing tool! aria-activedescendant is definitely on the todo list. We hope to have ANDI detecting that attribute and incorporating it into the output in the coming months.

**Comment by SSAgovAdmin** [comment]
We wanted to update you on the status of this feature request. This enhancement will be available in the next ANDI update planned to release within the next two weeks.
