### ISSUE TITLE
Edge - Adding ANDI bookmark

### ISSUE THREAD

**Issue by albatross666** [SSAgov/ANDI#26]
MS Edge now has additional features for bookmarks … the ability to import a file is handy … the instructions [https://www.ssa.gov/accessibility/andi/help/install.html](https://www.ssa.gov/accessibility/andi/help/install.html) for MS Edge are tricky, since developers generally have a bunch of browsers, each with their distinct set of bookmarks … so the import process is not ideal.

What can be easily done … a HTML file can be imported into MS Edge … this can be provided as a download, or instructions to self-create a bookmark file could be provided … the HTML for that file should be something like … 

```
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<DL><p>
    <DT><A HREF="javascript:void((function(){andiScript=document.createElement('script');andiScript.setAttribute('src','https://www.ssa.gov/accessibility/andi/andi.js');document.body.appendChild(andiScript)})());">ANDI SSA</A>
</DL><p>
```

To import the bookmark file, in MS Edge …

- Click on the ellipses (Alt X)
- Settings
- Import from another browser
- Import from file
- Select file
- Success is indicated by a message "All done!"
- Favorite is placed in a folder with the HTML file's name.

Hope this helps.

**Comment by SSAgovAdmin** [comment]
Thank you for providing these workaround instructions. If others ask about alternatives to install ANDI on Edge, we will refer to this as an option. Another option that we've heard about is a third party tool to manage Edge favorites.
