### ISSUE TITLE
Sites are starting to implement content security policies that block favlets

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#30]
Consider a simple extension for Chrome and Firefox that would load ANDI as an alterantive to the bookmarklet/Favlet approach.   Option 2: have someone else create such an extension which should be very simple to toggle ANDI on and off.

**Comment by SSAgovAdmin** [comment]
This is definitely something we've considered and even foresee for the day that browsers cease to allow bookmarklets and favelets to work. For now, developers and testers love how easy it is to install ANDI as a favelet. If someone would like to convert ANDI into an extension, by all means - it's open source, so fork away.
