### ISSUE TITLE
Increase support to show parent/ancestor structures to assist with ARIA widget testing

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#31]
I've noticed in some places the parent element is shown -- for things like groupings.  This is really helpful.  For other elements like role of tab -- there is no way with ANDI to confirm that role of tablist was used as an ancestor without switching to the structure view and turning on roles.  

In this tab example it would be helpful to know if an ancestor had the tablist role.
https://labs.levelaccess.com/index.php/ARIA_Tab_Role

In general inspection of ARIA structures is tricky with ANDI as not all properties are shown.  I understand that this makes the tool more complicated.  So another approach might be some sort of ARIA validator like this that might help automatically detect if the structure is correct or not.
http://whatsock.com/training/matrices/visual-aria.htm

**Comment by SSAgovAdmin** [comment]
We understand how this could be useful in testing. Expect increasing support of ancestor role detection in future updates.
