### ISSUE TITLE
Add implied ARIA live region roles to be shown when aria live regions are shown

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#33]
There are 5 implied aria live region roles that are live regions without use of aria-live -- these are status, log, alert, timer, and marquee.  Consider showing these when aria-live feature is activated.  Thanks

**Comment by SSAgovAdmin** [comment]
Thank you for bringing our attention to this. We will adjust sANDI's Live Regions mode to assume default values of aria-live when the element has one of the five live region roles.

Default aria-live="off"
https://www.w3.org/WAI/PF/aria/roles#marquee
https://www.w3.org/WAI/PF/aria/roles#timer
Default aria-live="polite"
https://www.w3.org/WAI/PF/aria/roles#log
https://www.w3.org/WAI/PF/aria/roles#status
Default aria-live="alert"
https://www.w3.org/WAI/PF/aria/roles#alert
