### ISSUE TITLE
Issue numbering / navigation issue

### ISSUE THREAD

**Issue by MarcusJTWhich** [SSAgov/ANDI#35]
It's weird that the "|<" and ">|" buttons are located nowhere near the number of issues found and that there's no indication of which issue you're currently looking at (e.g. "6/30")

**Comment by SSAgovAdmin** [comment]
The buttons in question cycle through all detected elements, not just the alerts. ANDI does not enumerate index numbers to the elements or issues because if the test page dynamically changes and ANDI is refreshed, the numbers will change or be reordered.
