### ISSUE TITLE
Question re Intranet testing

### ISSUE THREAD

**Issue by GerardoDespian** [SSAgov/ANDI#40]
We would like to use Andi to test our Intranet pages but are concerned that our secured content might be compromised.  Is it safe to use for our internal content?  Also, how often is the software updated?  Do users get notifications?

Thanks,

Gerardo

**Comment by SSAgovAdmin** [comment]
Security is a high priority for SSA. We also encourage individuals to follow the security policies laid out by their own organization.

SSA hosts an instance of ANDI on its website which is automatically updated; there are no update notifications. Updates typically include bug fixes and feature enhancements. [View the release notes here](https://www.ssa.gov/accessibility/andi/help/andi_release_notes.txt). [How to check the ANDI version](https://www.ssa.gov/accessibility/andi/help/howtouse.html#VersionPopup). With SSA's current release process, the code reflected in github may be a few versions behind the actual live executable code hosted on SSA's site. We at SSA are actively streamlining our release process to ensure that the two code bases (the github code and the SSA hosted instance) are identical in the future. 
 
When users launch ANDI, the browser downloads some javascript and css files and executes them locally. The ANDI instance hosted by SSA does not collect information from the pages it tests, nor does it send information anywhere else. Moreover, ANDI downloads an instance of jquery if it is not already present in the test page.

Some organizations may wish to stand-up their own instance of ANDI. This is one of the reasons we released ANDI's code as open source. When an organization hosts their own instance of ANDI, they will not receive automated updates from SSA. Furthermore, local installations should be monitored by the organization hosting the instance.
