### ISSUE TITLE
Download to disconnected network

### ISSUE THREAD

**Issue by mmeltzer-gov** [SSAgov/ANDI#41]
I would like to download the code to run on a network that is not connected to the Internet.  What do I need to download and what modifications would I need to make to the code to allow it to work?

**Comment by SSAgovAdmin** [comment]
Each release of ANDI on GitHub goes through the SSA's security testing protocol.  ANDI is a bookmarklet that downloads JavaScript files and stylesheets. The JavaScript is run locally on the user’s browser.  Organizations using ANDI (whether they use an instance posted to the internet or their own internally hosted instance) should follow their own information technology policies and security best practices.

Instructions for hosting ANDI locally [here](https://www.ssa.gov/accessibility/andi/help/install.html#hostYourOwn).
