### ISSUE TITLE
Offline Usage by Prison Inmates

### ISSUE THREAD

**Issue by pshikli** [SSAgov/ANDI#42]
We have a half dozen Trusted Testers certified by OAST and are looking to recertify to V5. ANDI is to replace the previous WAT tools required for that. Whereas we were able to load and use WAT to audit downloaded website copies, we cannot do so with ANDI because, as I understand it, ANDI makes an online call to https://www.ssa.gov/accessibility/andi/andi.js to operate.

Our problem is that Access2online is a joint-venture company run from inside a state prison. We have taught our inmates to do accessibility audits on local website copies, but prison rules prohibit inmates from live, unmonitored internet access. This is why they cannot use ANDI.

Is there a workaround, patch, setting, or adjustment we can make to operate ANDI without live internet access as we could with WAT?

We would like to continue to offer these hands-on job skills with a future to our inmates as part of their release preparation.

**Comment by SSAgovAdmin** [comment]
Since your testers are limited to your own intranet, your organization should host your own instance of ANDI. Instructions for [hosting your own ANDI can be found here](https://www.ssa.gov/accessibility/andi/help/install.html#hostYourOwn).
