### ISSUE TITLE
Offline Usage by Prison Inmates II

### ISSUE THREAD

**Issue by pshikli** [SSAgov/ANDI#44]
Although issue #42 Offline Usage by Prison Inmates by pshikli was closed on Mar 14, the prison's IT folks are unable to implement the recommendation given.

The recommendation was that since our Trusted Testers are limited to our own intranet because they are inmates at a state prison for women, our organization should host our own instance of ANDI via instructions for hosting our own ANDI found here: https://www.ssa.gov/accessibility/andi/help/install.html#hostYourOwn.

The prison's IT group reports that in order to host the offline version on the network, they would have to build a web server and change the javascript to point to the offline web server instead of what it currently points to.  Although they are quite familiar with sysadmin and security, none of the IT team are javascript programming experts.

Are there instructions or resources available to do this part?  We have a half dozen inmates who are certified Trusted Testers unable to get recertified without ANDI.

**Comment by SSAgovAdmin** [comment]
We spoke with the Trusted Tester Team and they would be happy to help you resolve this. Please reach out to them.
