### ISSUE TITLE
Local ANDI Install

### ISSUE THREAD

**Issue by pshikli** [SSAgov/ANDI#45]
Issue# 42 was about our need to load ANDI locally, as we did for its WAT predecessor, so that our 6 Trusted Testers certified by OAST who are inmates at a prison can use ANDI, a requirement to recertify. We were given an instruction URL that seemed to require some kind of Javascript patch.

When I submitted issue# 44 for help with that, I was told, "We spoke with the Trusted Tester Team and they would be happy to help you resolve this. Please reach out to them." With this, issue# 44 was closed on 04/22/19.

I have sent numerous emails and left voicemails to the Trusted Tester Team over the past month without response.  Since my understanding is that SSAgov is responsible for ANDI, could I trouble someone there to help us?  We need ANDI.

Cheers,
Peter Shikli
503-570-6831

**Comment by SSAgovAdmin** [comment]
Thank you for your diligence. We've reached out to the Trusted Tester team and given them your contact info.
