### ISSUE TITLE
Hyperlinks use color only

### ISSUE THREAD

**Issue by MichaelDHorton** [SSAgov/ANDI#46]
The ANDI help pages use only the color red to indicate hypertext. Not only is the underline removed, the help page's style moves away from the typical blue hypertext. The red chosen has a 4.5:1 contrast ration and thus meets the technical minimum threshold for color contrast, yet people who are colorblind often can't see red at all. 

![andi-color-only-hyperlinks](https://user-images.githubusercontent.com/31036819/59357301-96207b80-8cf8-11e9-8bca-fcf7eafc8895.jpg)

**Comment by SSAgovAdmin** [comment]
Thank you for giving the ANDI Help pages a thorough look! We take great pride in the accessibility of our site, and we are very grateful when concerns like this are brought to our attention.

The color and style of our links were carefully chosen by our design team. As noted, we made sure that the contrast ratio of the link text and the background is sufficient to WCAG standards. We also made sure that the color contrast between the link color and the surrounding paragraph text sufficiently meets current WCAG standards for our users with color blindness. Furthermore, when a user hovers over a link, an underline will appear and if a user tabs to a link, a focus ring will appear.

Here is some great info on the subject of [accessible link styling from WebAIM](https://webaim.org/techniques/hypertext/link_text#appearance).
