### ISSUE TITLE
Screen Reader Text Output for Entire Page

### ISSUE THREAD

**Issue by craigcecil** [SSAgov/ANDI#48]
John,

This is a feature request.

Would it be possible to add a feature that shows all of the screen reader text on the page--e.g., a printed version of what a screen reader would say for the entire page? I think that would be very useful, especially when reviewing accessibility with stakeholders, etc.  Maybe open another browser tab with this text? That would allow the user to print it out.

Craig

**Comment by SSAgovAdmin** [comment]
Although we can imagine the value in such a feature, ANDI's design purposefully avoids full page reports and focuses the tester on element by element evaluation. Some screen reader vendors offer this functionality in their products.
