### ISSUE TITLE
Javascript not running in Chrome

### ISSUE THREAD

**Issue by camcnutt** [SSAgov/ANDI#49]
It seems like my instance of Chrome refuses to recognize or run javascript in a bookmarklet.  I have javascript enabled, but nothing seems to work.  I tried a workaround by running the script through an html link and get an error saying "Uncaught TypeError: Cannot read property 'appendChild' of null" in the console.  Even if I could get that to work, it wouldn't open in the proper page.  The only thing that has worked is an embedded link, but again, I can't add that to the web pages I'm testing.

Please help.

**Comment by SSAgovAdmin** [comment]
Does ANDI work for you in other browsers, like IE, or is it only not launching in Chrome? Hit F12 and see if there is an error message in the console after launching ANDI. Here is some [troubleshooting information when ANDI won't launch](https://www.ssa.gov/accessibility/andi/help/faq.html#wontLaunch) that you may find helpful.

**Comment by JohnCotterSSA** [comment]
Have you had any success getting ANDI to work for you in Chrome? Please share what worked or what you have tried. We have 2 other reports of ANDI not working in Chrome. Most users are able use ANDI in Chrome.

**Comment by JohnCotterSSA** [comment]
Duplicate of issue https://github.com/SSAgov/ANDI/issues/52

**Comment by JohnCotterSSA** [comment]
Duplicate of https://github.com/SSAgov/ANDI/issues/52
