### ISSUE TITLE
Links/Button feature does not seem to cover buttons

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#5]
The links/button mode doesn't seem to address the button element, input type button/submit/reset, or ARIA buttons.  These items are not listed in this mode but are addressed by the Focusable elements mode.  Suggest changing the mode to just "links".

**Comment by SSAgov** [comment]
The current version of lANDI (links/buttons)(6.2.2) is detecting all types of buttons. Please provide a test page if you are still experiencing this issue.

**Comment by mraccess77** [comment]
My mistake -- for some reason I didn't see the buttons link to show the buttons -- but now I do!
