### ISSUE TITLE
ANDI is not working on Chrome

### ISSUE THREAD

**Issue by 508TrustedTester** [SSAgov/ANDI#50]
I followed the instructions to add ANDI to Chrome, but the javascript is not running. 
![image](https://user-images.githubusercontent.com/53572605/62302687-c824a300-b448-11e9-903f-d22b1e8e9bb5.png)
javascript:void((function(){andiScript=document.createElement('script');andiScript.setAttribute('src','https://www.ssa.gov/accessibility/andi/andi.js');document.body.appendChild(andiScript)})());

**Comment by SSAgovAdmin** [comment]
Is it working for you in other browsers besides Chrome?
What site are you trying to test with ANDI? Is it not working on all sites in chrome or just one in particular?

**Comment by 508TrustedTester** [comment]
It is working for me on other browsers besides Chrome.
I am testing an internal BLS website, http://sledtest92.bls.gov:2203/SLED/authorizationAction.do
ANDI is not working for all sites on Chrome.

**Comment by SSAgovAdmin** [comment]
Please refer to this trouble shooting guide to see if you can resolve the issue:
https://www.ssa.gov/accessibility/andi/help/faq.html#wontLaunch

**Comment by JohnCotterSSA** [comment]
Have you had any success getting ANDI to work for you in Chrome? Please share what worked or what you have tried. We have 2 other reports of ANDI not working in Chrome. Most users are able use ANDI in Chrome.

**Comment by 508TrustedTester** [comment]
It’s still not working for me. I tried reinstalling it, importing the bookmark from IE, and using Google Chrome Canary, but none of them worked.

**Comment by JohnCotterSSA** [comment]
Duplicate of https://github.com/SSAgov/ANDI/issues/52
