### ISSUE TITLE
ANDI Does not understand SVG content as an accessible label

### ISSUE THREAD

**Issue by dgibson666** [SSAgov/ANDI#51]
A widely tested and supported best practice for making SVGs accessible is to include a <title> element with the SVG. This is readable by just about every browser/screen reader combination. (See https://www.deque.com/blog/creating-accessible-svgs/)

However, ANDI flags buttons and links containing accessible SVGs using this technique as having "no accessible name, innerText, or [title]." This check should be updated to look for title elements within SVGs as well.

**Comment by SSAgovAdmin** [comment]
You are absolutely correct. We will address this issue in an upcoming release.

**Comment by JohnCotterSSA** [comment]
The latest release of ANDI (26.3.1) should now be calculating the accessible name of buttons and links which contain svg which contain a title element. Please let us know if you come across any issues.
