### ISSUE TITLE
ANDI Javascript not working in CHROME Browser

### ISSUE THREAD

**Issue by jbelzjr** [SSAgov/ANDI#52]
I am performing Section 508 Reviews on websites on https://www.epa.gov on a USEPA GFE Laptop..   ANDI functions properly when using IE and EDGE Browsers.   However, it does not run in CHROME.  The USEPA is pushing to make CHROME their primary browser so I need ANDI to work properly with it!!!!
I also have the same issue with ANDI working in IE and EDGE and not working in Chrome on my GDIT Corporate-issued Company Laptop.

I have also followed the FAQ troubleshooting page with no effect on the issue.   No messages are received on the Console indicating a Policy issue.   It could be an issue with both laptops blocking third-party access to cookies.   That, at least, appears to be the most common link between both experiences.   Also, I was able to ANDI to work in a Chrome browser using the Chrome App on my personal IPAD.   It took a bit of patience to get the bookmark loaded, but once available, it worked fine.

**Comment by SSAgovAdmin** [comment]
We're very sorry that you're having this issue. We are able to launch ANDI on chrome on the epa.gov site so we are not able to replicate this issue.

ANDI doesn't use "old-school" cookies but it does read and write to local storage using html 5 techniques. We tried going into chrome settings, turning off cookie permissions. Doing so did result in several error messages in the console relating to local storage when loading the epa site, but we were still able to get ANDI to launch.

Assuming that you successfully created the ANDI bookmark button in chrome, please right click on the bookmark, select edit, and compare the url string which should appear as 
javascript:void((function(){andiScript=document.createElement('script');andiScript.setAttribute('src','https://www.ssa.gov/accessibility/andi/andi.js');document.body.appendChild(andiScript)})());

If the string is different from the code above, please replace and try to launch ANDI again. If this does not resolve the issue, please provide a way to contact you directly.

**Comment by jbelzjr** [comment]
Thank you for the response.   I can be contacted at jbelzjr@aol.com, belzile.joseph@epa.gov.   Respond to one of the e-mails and I can supply a cell# for direct contact.

**Comment by arbowman** [comment]
I'm going through the Trusted Tester training, and am experiencing this issue in Chrome for both the official ANDI bookmarklet and the DHS testing ANDI one. Clicking on either bookmark doesn't do anything, even after clicking Edit and pasting in the full code again. I'm on my government laptop PC, so my Chrome (up-to-date, Version 77.0.3865.90 (Official Build) (64-bit)) is managed by my organization.

Given John's similar issue, I'm wondering if some agency CIO shops are starting to block scripts in bookmarks. I called our help desk and they have no idea, but I'll continue to pursue this issue internally. ANDI works normally for me in IE and Edge.

**Comment by JohnCotterSSA** [comment]
Here's an idea: Below is a favelet script that will throw a basic javascript alert.

Create a new favelet: right click on your browser favorites and select "Add page...". In the Name field put "Test Alert". In the URL field put this code:
`javascript:void((function(){alert("Hello")})());`

Select Save. Then launch the favelet you just created.

If you don't see the alert pop up, then it would confirm that javascript in bookmarks is indeed being blocked by your browser or admin, in which case ANDI will not be able to be launched either.

If you do see the pop up, something else that ANDI is trying to do is getting blocked.

We will add these troubleshooting steps to the FAQ.

**Comment by arbowman** [comment]
Thanks so much for this test, @JohnCotterSSA. That test favelet does not do anything in Chrome (no pop up), so it is almost certainly being blocked in our org's browser settings. I will follow up with our IT shop to try to get it unblocked.

**Comment by Ottis-Bishop** [comment]
@JohnCotterSSA that favelet displays for me, what could be something that is blocking the ANDI page from displaying or is this kind of a case by case issue and should be something investigated on the website's end?
