### ISSUE TITLE
Offer the Help pages as part of the repo

### ISSUE THREAD

**Issue by jorluiseptor** [SSAgov/ANDI#53]
I suggest including the Help pages for installation instructions as part of this repository. Our agency is planning to use this tool and it will save us time to re-use the help files / pages that were created by the SSA. (https://www.ssa.gov/accessibility/andi/help/) 

thanks!

**Comment by JohnCotterSSA** [comment]
Thank you for this suggestion. We will be adding the help pages into the repo soon.

**Comment by JohnCotterSSA** [comment]
As requested, the ANDI Help pages have been incorporated into the github repo with the code. From now on, clones/forks of ANDI will include the help files.
