### ISSUE TITLE
ARIA grid has no [role=row] rows still an issue

### ISSUE THREAD

**Issue by slvy** [SSAgov/ANDI#54]
This bug was closed a few weeks ago but I am still getting the same error message with the latest ANDI.

https://github.com/SSAgov/ANDI/issues/47

**Comment by JohnCotterSSA** [comment]
We want to get this issue successfully resolved for you. Can you please provide a link to a sample page so that we can reproduce the issue?

**Comment by vveesseelliinnaa** [comment]
Hi, @cotter-john,
You can observe the issue in the following demo even though each row has an assigned "role='row'" attribute:
https://demos.telerik.com/kendo-vue-ui/grid/columns/column-menu/flter-only-custom-icon?theme=default-ocean-blue

<img width="1878" height="1150" alt="Image" src="https://github.com/user-attachments/assets/750400ca-1a73-4e6c-a467-7e93717d444c" />
