### ISSUE TITLE
Andi not working on asp.net with telerik RadWindow ui

### ISSUE THREAD

**Issue by MaduroToro247** [SSAgov/ANDI#57]
I'm evaluating a web application build on asp.net with telerik ui componets. Andi works for the most part except when a RadWindow is opened (modal dialog box). if andi is open before the RW is initiated, the window renders a blank dialog and andi freezes. If andi is intiated while a RadWindow is up, andi never comes up.

This happens in IE and Chrome. No other browsers an available in the environment.

Any thoughts? Thanks in advance.
Jeff

**Comment by JohnCotterSSA** [comment]
Generally, ANDI works with most modal dialog box implementations. If you could provide a sample page, we could help to diagnose the issue.
