### ISSUE TITLE
Elements with ARIA role of link are not shown in the links/button mode

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#6]
Elements with role of link are not shown in the links mode -- they are shown under the Focusable Elements mode.  Is this by design?

**Comment by SSAgov** [comment]
The current version of lANDI (links/buttons)(6.2.2) is detecting role=link elements. Please provide a test page if you are still experiencing this issue.

**Comment by mraccess77** [comment]
This is now working but was not previously working for me.  Thanks
