### ISSUE TITLE
What is the use case for ANDI?

### ISSUE THREAD

**Issue by mgifford** [SSAgov/ANDI#62]
I'm not sure how ANDI compares with WAVE, Axe, or Accessibility Insights. It's a bookmarklet as I see it so seems like it might be easier for some organizations to install.  Is it more broadly available to organizations who don't have full access to add new extensions? 

I'm just trying to understand why you'd use ANDI over some of these other tools.  Or perhaps when you'd use them in conjunction with other tools.

**Comment by JohnCotterSSA** [comment]
The main use case for ANDI is manual accessibility testing. [More info about ANDI here](https://www.ssa.gov/accessibility/andi/help/install.html). ANDI provides limited screen reader emulation as well as automated page scanning for accessibility issues.

Please compare ANDI to these other tools and share your experience here.
