### ISSUE TITLE
Microsoft Edge Chromium Compatibility 

### ISSUE THREAD

**Issue by alan-harper** [SSAgov/ANDI#64]
MEC is newly deployed in my clients enterprise environment. The ANDI help guide does not specify if ANDI is compatible. I've installed it personally and have not encountered any issue but I wanted to mention the help guide may need to be updated.

**Comment by JohnCotterSSA** [comment]
Thanks for the heads up. On the ANDI Install page, we've made an update to indicate that Edge Chromium is compatible with ANDI.
