### ISSUE TITLE
Tables module not displaying

### ISSUE THREAD

**Issue by clwalker95** [SSAgov/ANDI#66]
On both Firefox and IE11 (haven't tried on Chrome), the tables module does not display in the list of modules on hover. If I click on 'focusable elements' I see the tables module briefly but cannot click on it. 

![image](https://user-images.githubusercontent.com/62437367/77181422-aa708080-6aa1-11ea-8f79-6ba7697b2026.png)

**Comment by JohnCotterSSA** [comment]
The tables module only appears in the list when ANDI detects tables on the page. Please let us know if you find a page where there are tables on the page and the tables module is not appearing in the list.

**Comment by clwalker95** [comment]
I was on a page with a table on the DHS 508 Trusted Trainer incremental exam and it was not working. I thought this was part of the test and tried DNA and FAIL, which both did not work. I am trying it on another page now with a table and it works fine.
