### ISSUE TITLE
Page Content ( Table Columns, Rows) Disappears when ANDI Tool Bar is initiated.

### ISSUE THREAD

**Issue by mohammad-saleem** [SSAgov/ANDI#69]
[ANDI Tool Issue.docx](https://github.com/SSAgov/ANDI/files/4731651/ANDI.Tool.Issue.docx)
When I open the FSM>>> OBIEE>>>Project and Task Status of Funds Report>>> As you can see in below screen Column & rows are populated with data cells. 
When i initiate ANDI tool bar, all the Data in Columns, Rows are disappeared in below screen shot:

**Comment by JohnCotterSSA** [comment]
Thanks for reporting this issue. For security reasons, we are not going to open a docx file. Please open a new issue and paste any screenshots directly into the comment box. Thank you for understanding.

**Comment by mohammad-saleem** [comment]
Sure I’ll do that. Thanks
