### ISSUE TITLE
Area elements don't seem to be shown by the focusable elements on Hover

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#7]
Area elements used in image maps don't appear to be shown by ANDI images/graphics but are shown in focusable elements.  However, no border appears with mouse hover in the focusable elements module.  Tabbing or using next/previous in focusable elements mode does highlight the area elements.

**Comment by SSAgov** [comment]
Area elements are inspectable using either “focusable elements” or “graphics/images”. Please provide a test page where area elements are not inspectable in “graphics/images”.  Unfortunately, current browsers do not implement CSS border or outline modification for <area> elements (stackoverflow discussion: https://stackoverflow.com/questions/10499446/make-a-border-to-the-areas-in-the-image-maps), therefore ANDI cannot add additional highlighting to <area> elements.

**Comment by jfemia10** [comment]
[**]()
