### ISSUE TITLE
Page Content ( Table Columns, Rows) Disappears when ANDI Tool Bar is initiated

### ISSUE THREAD

**Issue by mohammad-saleem** [SSAgov/ANDI#70]
When I open the FSM>>> OBIEE>>>Project and Task Status of Funds Report>>> As you can see in below screen Column & rows are populated with data cells. 
When i initiate ANDI tool bar, all the Data in Columns, Rows are disappeared in below screen shot:
![image](https://user-images.githubusercontent.com/66435342/83799915-8ec65080-a674-11ea-9739-d72fc6256071.png)
![image](https://user-images.githubusercontent.com/66435342/83799932-938b0480-a674-11ea-9aa8-884b96e13d93.png)

**Comment by JohnCotterSSA** [comment]
Are you able to determine if the table is contained within an iframe? Sometimes, content generated dynamically and placed within an iframe will disappear when ANDI is launched. This is a browser limitation. If that is the case, this content will not be able to be tested using ANDI.

**Comment by mohammad-saleem** [comment]
This content is not residing in the iFrame, it is actually Data Table as observed in the Screen shot above, i have tried using the different browsers MS EDGE( Version 81.0.416.72), Mozilla Firefox, IE 11 all are having same issue. Thanks
