### ISSUE TITLE
Module Selection Menu partially hidden

### ISSUE THREAD

**Issue by JoelMcKinnon** [SSAgov/ANDI#72]
For the web page I need to test, an open source web application developed and maintained by NASA called Open MCT, the Module Selection Menu is almost always at least partially hidden beneath the test page content.

![ANDI menu bug](https://user-images.githubusercontent.com/6541399/86031321-8a2e5700-b9ea-11ea-85a9-41ec19effd13.png)

I see this behavior in Firefox (68.9.0), Chrome (83.0.4103.116), and Safari (13.1.1) on a Macbook Pro running macOS Mojave (10.14.6).

Other publicly available websites such as google.com, stackoverflow.com, and ssa.gov do not exhibit this problem.

**Comment by JohnCotterSSA** [comment]
Hi Joel. Sorry for this difficulty. Our best guess as to what is occurring is that the test page has some CSS that is overriding ANDI's CSS, such as a higher z-index value. If you are able to provide us the url of the test page, we can look into the issue. 

For the time being, you should be able to use the keyboard arrow keys to make the module selection and the enter key to activate. This won't allow you to see the obscured modules, but you should still be able to select and activate them.

**Comment by JoelMcKinnon** [comment]
Hi John,

Thanks for the quick response. Unfortunately, the arrow keys have no effect on the menu. I was able to workaround it by using devtools to set the height of the ANDI508 section to 220px, but it is a little awkward. I first looked to see if the web app I’m testing had a z-index set but it does not.

Open MCT is open source and you can create a local build of it here: https://github.com/nasa/openmct

There is a link to a live demo for the app, which actually has no problem with ANDI. I’m going to work with our UX guy and see if I can figure out how it’s interfering with the ANDI component only in the local build.

Joel

**Comment by JohnCotterSSA** [comment]
Okay, keep us updated on your findings.

**Comment by JoelMcKinnon** [comment]
I have a nice workaround for now. Using the Stylebot chrome extension I set a rule for localhost:8080** (any url beginning with localhost:8080)
#ANDI508:focus-within {
  height: 220px;
}

Upon clicking anywhere within the ANDI section it expands to provide enough room to show the full menu. Clicking out of the section it collapses to show more of the test page.

I will let you know if I ever figure out why this is all necessary, but it looks good for now. Incidentally I love the tool!

Joel

**Comment by JohnCotterSSA** [comment]
Glad you're loving ANDI!

That's a neat CSS trick. I'll close this issue for now since you have a good workaround. Feel free to poke it again if anything else comes up.

**Comment by JoelMcKinnon** [comment]
Will do.

BTW – My contract is up end of July and I’m looking for a new gig in web accessibility. My contract is up end of July. If you know of anyone hiring front end devs with a11y experience, please let me know. Personal email is joelmckinnon@icloud.com<mailto:joelmckinnon@icloud.com>.

Joel
