### ISSUE TITLE
ANDI Not Refreshing Correctly

### ISSUE THREAD

**Issue by krbohon** [SSAgov/ANDI#73]
ANDI doesn't seem to be refreshing like it used to when I move to a different tab in my system's UI. I'm recieving 508 alerts that aren't there, and the only way to clear the alerts is to clear my cache. This issue started sometime last week.

**Comment by JohnCotterSSA** [comment]
Sorry you are having trouble. There hasn't been an ANDI update in a little while, so no new code may have caused this. Refreshing the test page should completely remove anything ANDI has added. If you can provide some more details or step by step instructions on how to produce the issue, we can try to assist you.
