### ISSUE TITLE
This probably has to do with the application's CSS overriding ANDI's CSS. If you can provide some sample links, we can reproduce the issue and look into increasing the specificity of the CSS definitions.

### ISSUE THREAD

**Issue by Ciampi10** [SSAgov/ANDI#77]
This probably has to do with the application's CSS overriding ANDI's CSS. If you can provide some sample links, we can reproduce the issue and look into increasing the specificity of the CSS definitions.

_Originally posted by @JohnCotterSSA in https://github.com/SSAgov/ANDI/issues/59#issuecomment-573638376_

**Comment by JohnCotterSSA** [comment]
Hi. If you are trying to provide a sample link to a test page with an issue, please paste it into the issue comment box.
