### ISSUE TITLE
Linearize with modal

### ISSUE THREAD

**Issue by arashsoheili** [SSAgov/ANDI#79]
It seems that linearize doesn't work properly with modal. If you check the linearize then active modal then it sometimes works and pushed modal to the bottom. But if you activate modal then check linearize the modal stays in the middle. It doesn't seem to behave consistently with modal.

**Comment by JohnCotterSSA** [comment]
Hi there.

The linearize feature is an advanced setting that is used to test for the meaningful sequence of elements on the page. Elements that have been adjusted by linearize will have a teal halo outline.

ANDI's linearize feature looks for elements that have certain settings to their CSS position property. Typically, a modal window has its CSS position set to absolute or fixed, and the linearize feature will detect it. When the linearize feature is activated, it sets all positions to "position: static" which will, most likely, send the modal to the bottom of the screen.

One reason for your observation of inconsistency is that ANDI does not continually scan the DOM. Therefore, When the modal appears after ANDI has already been launched, ANDI will not be aware that the modal has appeared. Try refreshing ANDI after the modal appears and you should see better consistency.

**Comment by arashsoheili** [comment]
@JohnCotterSSA Thank you for your response. I tried the refresh but still doesn't work. We are using React app with Swal2 modal implementation in myUSCIS.
