### ISSUE TITLE
ANDI does not have a linearize mode to help check for reading order

### ISSUE THREAD

**Issue by mraccess77** [SSAgov/ANDI#8]
It may be useful to apply a style to a page like changing all content to display block to force a linear view of the page.  This can help to check the reading order without using assistive technology.

**Comment by SSAgov** [comment]
Thank you for contributing this interesting idea to ANDI. Our team will keep this idea in mind as development continues. Currently there are no plans to implement this.

**Comment by mraccess77** [comment]
An easy change that I do is to apply display:block to all content via CSS on the page forcing a linear order while preserving other aspects of CSS.   This test is really the last manual inspection test that is needed and readily achievable to move a baseline test process to ANDI exclusively.  Other automated tests are possibilities but can be tested manually.
