### ISSUE TITLE
ANDi is not responding in a Modal Window

### ISSUE THREAD

**Issue by vprentice** [SSAgov/ANDI#80]
I have a client that has stated that she is not able to get ANDi to work within a Modal Window. The tool will however work everywhere else in the application?

Are there any none issues with ANDi working within Modal Windows and if so, is there a work around?

Best regards, 
![TA Question](https://user-images.githubusercontent.com/34749872/88223577-af069a80-cc35-11ea-9cdf-f279580000dd.jpg)

**Comment by JohnCotterSSA** [comment]
Hi there. ANDI does not constantly scan the DOM for changes. After the modal appears, refresh ANDI and it should detect the content within the modal.

**Comment by vprentice** [comment]
Thank you for your reply John, I will inform the client.

Best regards,

Vince
