### ISSUE TITLE
ANDI mangled appearance when testing TopDesk

### ISSUE THREAD

**Issue by seattleguitarman** [SSAgov/ANDI#81]
Hi.  I'm brand new to GitHub and would have written directly to ANDI people via email if that was the better way to go but it looked like going here is the suggested path.  I'm just getting familiar with ANDI and was trying it out on TopDesk which we'll be rolling out at my institution soon.  When I activate ANDI it doesn't appear fully and instead has text splayed out down the left edge of the browser window (Firefox) and the far right hand icons for ANDI aren't reachable.  Thought it doing the Trusted Tester training which I'm mid-way through, that there was mention of cases where things break the functionality of the tool.  

Wonder what in TopDesk migh be messing with the tool's use that isn't happening on other web sites I've tried.

![ANDI-TopDeskGlitch](https://user-images.githubusercontent.com/69641599/90174067-430de280-dd5a-11ea-8f2d-6e384a4ea54b.jpg)

**Comment by JohnCotterSSA** [comment]
Thanks for the explanation here. We want to get this fixed for you.

We went to the topdesk.net site and didn't see the issue. Is there a direct link to a page where we can reproduce the issue? We'll need to poke around in the application's CSS to help us diagnose the issue. Thanks!

**Comment by seattleguitarman** [comment]
Since it is a helpdesk/support tracking tool we're just gearing up to rollout I don't think I can provide another access to that as it uses user/password to get in.

Doug Hayman


________________________________

**Comment by JohnCotterSSA** [comment]
Understood. Without access to a test page, we can only guess as to what the problem may be. 

However, we just pushed an update to ANDI that will enforce CSS position:static to many of the ANDI elements which may fix the issue. Please clear your browser cache and try ANDI again and let us know if anything changes.

**Comment by seattleguitarman** [comment]
Thanks John, I’ll try that.

Sent from my iPhone
Doug Hayman

On Aug 14, 2020, at 11:42 AM, John Cotter <notifications@github.com> wrote:

﻿

Understood. Without access to a test page, we can only guess as to what the problem may be.

However, we just pushed an update to ANDI that will enforce CSS position:static to many of the ANDI elements which may fix the issue. Please clear your browser cache and try ANDI again and let us know if anything changes.

**Comment by seattleguitarman** [comment]
John,

That did the trick.

Thanks,

Doug Hayman


________________________________

**Comment by JohnCotterSSA** [comment]
Wonderful! I'll close the ticket. Thanks for bringing this to our attention.
