### ISSUE TITLE
pseudo_before_after Help URL Broken

### ISSUE THREAD

**Issue by dgibson666** [SSAgov/ANDI#88]
For the "Content has been injected using CSS pseudo-elements ::before or ::after." warnings, the URL that is constructed for help (when clicking it) is bad. It's trying to insert a query string, but the ? ends up missing and tries to display this page, which shows a file not found message:

https://www.ssa.gov/accessibility/andi/help/alerts.htmlpseudo_before_after

**Comment by JohnCotterSSA** [comment]
Thank you for pointing out this issue. It has been fixed in ANDI 27.3.1
