### ISSUE TITLE
ANDI suddenly not loading on Mac or Windows

### ISSUE THREAD

**Issue by zdhaughton** [SSAgov/ANDI#89]
I have been using ANDI for a while but in the last few weeks it has stopped loading on either Mac or Windows. Even the SSA gov home page was not loading.
Environments:
1. Latest Mac OS version with latest Chrome 
2. Windows 10 with latest Edge and Chrome versions

I have tried the following to resolve:
1. Full reboot
2. New install of ANDI
3. Cleared cache
4. Tried Chrome, Firefox and Edge

Nothing has solved the problem to date.
Please advise

**Comment by JohnCotterSSA** [comment]
Hi there. Sorry you are experiencing this issue.

ANDI is hosted at ssa.gov which explains why if ssa.gov is loading for you, then ANDI wouldn't work. The website ssa.gov should never be offline, so we can only assume that your ISP is blocking the site or a firewall is blocking the site. There isn't anything we can do to help resolve the issue.

Once you are able to restore connection to ssa.gov, ANDI should work again for you.
