### ISSUE TITLE
Content Security Policy directive prevent ANDI to be loaded

### ISSUE THREAD

**Issue by icks1313** [SSAgov/ANDI#91]
Hello, 

is there any way in the future to prevent this type or error? 

_VM109:1 [Report Only] Refused to load the script 'https://www.ssa.gov/accessibility/andi/andi.js' because it violates the following Content Security Policy directive: "script-src maps.googleapis.com server.adform.net cdn.adtelligence.de 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback._

it currently prevent from using ANDI

Thanks!

**Comment by JohnCotterSSA** [comment]
Sorry that you are being prevented from testing with favelets like ANDI because of the CSP on that page. Please read this information about [how to use ANDI to test pages with content security policy](https://www.ssa.gov/accessibility/andi/help/faq.html#wontLaunch).
