### ISSUE TITLE
When on focusable elements, it does not show "Focusable elements Found:", and if you go to another area and then back, the results form that area are shown for focusable elements

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#94]
When you go to a site (boton.gov) and open ANDI, nothing shows up for focusable elements. If you go to images and back to focusable elements, the "Images Found:" statement is still there. It happens also for other types of areas for ANDI.

**Comment by JohnCotterSSA** [comment]
Hi There. It looks like there is a JavaScript error in ANDI appearing in the console when it is run against boston.gov. This explains the strange behavior on that site. We'll look into it ASAP.

**Comment by JohnCotterSSA** [comment]
We fixed this bug today in version 27.3.2 of ANDI. Please comment on this issue if it is not resolved for you.

You may need to clear your browser's cached images and files to ensure that you grab the latest version of ANDI.
