### ISSUE TITLE
There should be better instructions for hosting your own instance of ANDI

### ISSUE THREAD

**Issue by ollie-iterators** [SSAgov/ANDI#95]
I found that the instructions for hosting your own instance of ANDI were not complete enough to make it work. When I tried using "file://" and then adding the filepath to the downloaded ANDI files, it did not work, and using "https://github.com/" then the rest of the link for my fork did not work as well.

The thing that worked for creating my own version of ANDI was to create a GitHub Page version of my forked repository.

Because of this, I think better instructions for creating your own version of ANDI would be: (Note: These instructions may not be fully accessible, so they may need to be changed)
1. Create your own fork of ANDI
2. Click on the Settings button
3. Go to the GitHub Pages section of the page you are on
4. Enable the creation of a GitHub Page version of the ANDI fork and go through the process of creating the GitHub Page
5. Use the link for the GitHub Page and replace the host_URL in andi.js with the GitHub Page url for the andi folder, and use the same url used in andi.js to replace the [ALTERNATE HOST] text in the favelet's launch script used for your instance of ANDI

**Comment by JohnCotterSSA** [comment]
Thanks for this feedback. The suggestion you provided is good. It's possible to host the instance on any server, not just a github page server. We'd like to keep the instructions more general. 

Re-reading the instructions, it looks like we assumed the step to upload the files to a server. Adding that step should help to clarify.

In regards to hosting ANDI locally from file://, it does generally work.  The line should look something like this:
`var host_url = "file://C:/WS/repos/....../andi/";`

**Comment by JohnCotterSSA** [comment]
We've tried to clarify the custom install instructions. Let us know if you think it needs additional fine tuning. Note: It has been [moved to the FAQ page](https://www.ssa.gov/accessibility/andi/help/faq.html#hostYourOwn)
